### ISSUE TITLE
Lock screen or status bar widget to show media info and control them 

### ISSUE THREAD

**Issue by mvardin** [MicrosoftDocs/CommunityToolkit#334]
I'm using MediaElement to create a music player but I need to show media info in lock screen and status bar

Is there any way to show and control media info in lock screen and status bar like other music player?

**Comment by bijington** [comment]
@jfversluis sorry for the tag but you seem to be our MediaElement expert. Do you know if this 'just' boils down to changing things like the AVAudioSession category on iOS and whatever the equivalent (if there is) on Android?

**Comment by jfversluis** [comment]
I don't know about Android to be honest, but for iOS I had this in the Xamarin days: https://www.youtube.com/watch?v=1XVjsUO-Ayw

I think that should mostly just work, but you'll have to adapt it to .NET MAUI

**Comment by bijington** [comment]
I'm going to close this as there hasn't been any update since November. Feel free to reopen if you want further detail although I would suggest that you use a discussion on the code repository https://github.com/CommunityToolkit/Maui as this is likely monitored a lot more than the documentation repository
